version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=registry,ref=python:3.9-slim
    volumes:
      - .:/app  # Mount the host's ./app directory to /app inside the container
    ports:
      - "8501:8501"  # Expose port 8501 internally (no need for direct external access)
    environment:
      - FLASK_ENV=production
      - INTERACTIVE_MODE=false
    command: streamlit run app.py  # Adjust this based on your app's entry point
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Optional for networking between container and host

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./config/nginx-entrypoint.sh:/docker-entrypoint.d/40-replace-env-vars.sh:ro
    ports:
      - "80:80"  # HTTP port (for Certbot validation)
      - "443:443"  # HTTPS port
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - app

